### ISSUE TITLE
SyntaxError: invalid syntax under using gpx-cmd-tools 

### ISSUE THREAD

**Issue by squeezer44** [tkrajina/gpx-cmd-tools#4]
Hi *,

is there an error in your Package gpx-cmd-tools 0.0.1   or did I  misunderstand your documentation?
I'm looking forward to your answer
Thx

- Enviroment
Python 3.8.2  
gpx-cmd-tools 0.0.1  
gpxpy 1.4.2  

- Issue
As described in https://github.com/tkrajina/gpx-cmd-tools#gpxinfo I used the Pyhton console with this code:  
`gpxinfo 2021-09-25_07-47-12-UTC_be9e18af-b133-4469-9058-45386372d3ce.gpx`  
and got this result:  
```
gpxinfo 2021-09-25_07-47-12-UTC_be9e18af-b133-4469-9058-45386372d3ce.gpx
  File "<ipython-input-27-689b37028f27>", line 1
    gpxinfo 2021-09-25_07-47-12-UTC_be9e18af-b133-4469-9058-45386372d3ce.gpx
            ^
SyntaxError: invalid syntax
```

**Comment by tkrajina** [comment]
https://github.com/tkrajina/gpx-cmd-tools#gpxinfo doesn't say you need to use it in a python console. It says those are command line tools (which are run in your shell).
